nyc_regions = {
    "The Bronx": [
        '138 ST'
        '138 St-Grand Concourse',
        '149 St-Grand Concourse',
        '161 St-Yankee Stadium',
        '167 St',
        '167 St',
        '170 St',
        '170 St',
        '174 St',
        '174-175 Sts',
        '176 St',
        '182-183 Sts',
        '183 St',
        '219 St',
        '225 St',
        '231 St',
        '233 St',
        '238 St',
        '3 Av-138 St',
        '3 Av-149 St',
        'Allerton Av',
        'Baychester Av',
        'Bedford Park Blvd',
        'Bedford Park Blvd-Lehman College',
        'Bronx Park East',
        'Brook Av',
        'Buhre Av',
        'Burke Av',
        'Burnside Av',
        'Castle Hill Av',
        'Cypress Av',
        "East 143 St-St Mary's St",
        'East 149 St',
        'East 180 St',
        'Eastchester-Dyre Av',
        'Elder Av',
        'Fordham Rd',
        'Fordham Rd',
        'Freeman St',
        'Gun Hill Rd',
        'Gun Hill Rd',
        'Hunts Point Av',
        'Intervale Av',
        'Jackson Av',
        'Kingsbridge Rd',
        'Kingsbridge Rd',
        'Longwood Av',
        'Middletown Rd',
        'Morris Park',
        'Morrison Av-Soundview',
        'Mosholu Pkwy',
        'Mt Eden Av',
        'Nereid Av',
        'Norwood-205 St',
        'Parkchester',
        'Pelham Bay Park',
        'Pelham Pkwy',
        'Pelham Pkwy',
        'Prospect Av',
        'Simpson St',
        'St Lawrence Av',
        'Tremont Av',
        'Van Cortlandt Park-242 St',
        'Wakefield-241 St',
        'West Farms Sq-East Tremont Av',
        'Westchester Sq-East Tremont Av',
        'Whitlock Av',
        'Woodlawn',
        'Zerega Av'
    ],
    "Brooklyn": [
        '15 St-Prospect Park',
        '18 Av',
        '18 Av',
        '18 Av',
        '20 Av',
        '20 Av',
        '25 Av',
        '25 St',
        '36 St',
        '4 Av /9 St',
        '45 St',
        '50 St',
        '53 St',
        '55 St',
        '59 St',
        '7 Av',
        '7 Av',
        '71 St',
        '77 St',
        '79 St',
        '8 Av',
        '86 St',
        '86 St',
        '9 Av',
        'Alabama Av',
        'Atlantic Av',
        'Atlantic Av-Barclays Ctr',
        'Avenue H',
        'Avenue I',
        'Avenue J',
        'Avenue M',
        'Avenue N',
        'Avenue P',
        'Avenue U',
        'Avenue U',
        'Avenue U',
        'Avenue X',
        'Bay 50 St',
        'Bay Pkwy',
        'Bay Pkwy',
        'Bay Pkwy',
        'Bay Ridge Av',
        'Bay Ridge-95 St',
        'Bedford Av',
        'Bedford-Nostrand Avs',
        'Bergen St',
        'Bergen St',
        'Beverley Rd',
        'Beverly Rd',
        'Brighton Beach',
        'Broadway',
        'Broadway Junction',
        'Bushwick Av-Aberdeen St',
        'Canarsie-Rockaway Pkwy',
        'Carroll St',
        'Central Av',
        'Chauncey St',
        'Church Av',
        'Church Av',
        'Church Av',
        'Clark St',
        'Classon Av',
        'Cleveland St',
        'Clinton-Washington Avs',
        'Clinton-Washington Avs',
        'Coney Island-Stillwell Av',
        'Cortelyou Rd',
        'Court St /Borough Hall',
        'Crescent St',
        'Crown Heights-Utica Av',
        'Cypress Hills',
        'DeKalb Av',
        'DeKalb Av',
        'Ditmas Av',
        'East 105 St',
        'Eastern Pkwy-Brooklyn Museum',
        'Euclid Av',
        'Flatbush Av-Brooklyn College',
        'Flushing Av',
        'Flushing Av',
        'Fort Hamilton Pkwy',
        'Fort Hamilton Pkwy',
        'Fort Hamilton Pkwy',
        'Franklin Av /Botanic Garden',
        'Franklin Av',
        'Fulton St',
        'Gates Av',
        'Graham Av',
        'Grand Army Plaza',
        'Grand St',
        'Grant Av',
        'Greenpoint Av',
        'Halsey St',
        'Halsey St',
        'Hewes St',
        'High St',
        'Hoyt St',
        'Hoyt-Schermerhorn Sts',
        'Jay St-MetroTech',
        'Jefferson St',
        'Junius St',
        'Kings Hwy',
        'Kings Hwy',
        'Kings Hwy',
        'Kingston Av',
        'Kingston-Throop Avs',
        'Knickerbocker Av',
        'Kosciuszko St',
        'Lafayette Av',
        'Liberty Av',
        'Livonia Av',
        'Lorimer St',
        'Lorimer St /Metropolitan Av',
        'Marcy Av',
        'Montrose Av',
        'Morgan Av',
        'Myrtle Av',
        'Myrtle-Willoughby Avs',
        'Myrtle-Wyckoff Avs',
        'Nassau Av',
        'Neck Rd',
        'Neptune Av',
        'Nevins St',
        'New Lots Av',
        'New Lots Av',
        'New Utrecht Av /62 St',
        'Newkirk Av',
        'Newkirk Plaza',
        'Norwood Av',
        'Nostrand Av',
        'Nostrand Av',
        'Ocean Pkwy',
        'Park Pl',
        'Parkside Av',
        'Pennsylvania Av',
        'President St',
        'Prospect Av',
        'Prospect Park',
        'Ralph Av',
        'Rockaway Av',
        'Rockaway Av',
        'Saratoga Av',
        'Sheepshead Bay',
        'Shepherd Av',
        'Smith-9 Sts',
        'Sterling St',
        'Sutter Av',
        'Sutter Av-Rutland Rd',
        'Union St',
        'Utica Av',
        'Van Siclen Av',
        'Van Siclen Av',
        'Van Siclen Av',
        'West 8 St-New York Aquarium',
        'Wilson Av',
        'Winthrop St',
        'York St'
    ],
    "Manhattan": [
        '1 Av',
        '103 St',
        '103 St',
        '103 St',
        '110 St',
        '116 St',
        '116 St',
        '116 St',
        '116 St-Columbia University',
        '125 St',
        '125 St',
        '125 St',
        '125 St',
        '135 St',
        '135 St',
        '137 St-City College',
        '14 St /8 Av',
        '14 St /6 Av',
        '14 St-Union Sq',
        '145 St',
        '145 St',
        '145 St',
        '155 St',
        '155 St',
        '157 St',
        '163 St-Amsterdam Av',
        '168 St',
        '175 St',
        '18 St',
        '181 St',
        '181 St',
        '190 St',
        '191 St',
        '2 Av',
        '207 St',
        '215 St',
        '23 St',
        '23 St',
        '23 St',
        '23 St',
        '23 St',
        '28 St',
        '28 St',
        '28 St',
        '3 Av',
        '33 St',
        '34 St-Herald Square',
        '34 St-Hudson Yards',
        '34 St-Penn Station',
        '34 St-Penn Station',
        '42 St-Bryant Pk /5 Av',
        '47-50 Sts-Rockefeller Center',
        '49 St',
        '5 Av-53 St',
        '5 Av-59 St',
        '50 St',
        '50 St',
        '57 St',
        '57 St-7 Av',
        '59 St-Columbus Circle',
        '66 St-Lincoln Center',
        '68 St-Hunter College',
        '7 Av',
        '72 St',
        '72 St',
        '72 St',
        '77 St',
        '79 St',
        '8 St-New York University',
        '81 St-Museum of Natural History',
        '86 St',
        '86 St',
        '86 St',
        '86 St',
        '96 St',
        '96 St',
        '96 St',
        '96 St',
        'Astor Place',
        'Bowery',
        'Bowling Green',
        'Broad St',
        'Broadway-Lafayette St /Bleecker St',
        'Brooklyn Bridge-City Hall /Chambers St',
        'Canal St',
        'Canal St',
        'Canal St',
        'Cathedral Pkwy-110 St',
        'Cathedral Pkwy-110 St',
        'Central Park North-110 St',
        'Chambers St',
        'Chambers St /WTC /Park Place',
        'Christopher St-Sheridan Sq',
        'City Hall',
        'Delancey St /Essex St',
        'Dyckman St',
        'Dyckman St',
        'East Broadway',
        'Franklin St',
        'Fulton St',
        'Grand Central-42 St',
        'Grand St',
        'Harlem-148 St',
        'Houston St',
        'Inwood-207 St',
        'Lexington Av /59 St',
        'Lexington Av-53 St /51 St',
        'Lexington Av-63 St',
        'Marble Hill-225 St',
        'Prince St',
        'Rector St',
        'Rector St',
        'Roosevelt Island',
        'South Ferry /Whitehall St',
        'Spring St',
        'Spring St',
        'Times Sq-42 St /42 St',
        'Wall St',
        'Wall St',
        'West 4 St-Washington Sq',
        'WTC Cortland'
    ],
    "Queens": [
        '103 St-Corona Plaza',
        '104 St',
        '104 St',
        '111 St',
        '111 St',
        '111 St',
        '121 St',
        '169 St',
        '21 St',
        '21 St-Queensbridge',
        '30 Av',
        '33 St-Rawson St',
        '36 Av',
        '36 St',
        '39 Av- Dutch Kills',
        '40 St-Lowery St',
        '46 St',
        '46 St-Bliss St',
        '52 St',
        '63 Dr-Rego Park',
        '65 St',
        '67 Av',
        '69 St',
        '74-Bway /Jackson Hts-Roosevelt Av',
        '75 Av',
        '75 St-Elderts Ln',
        '80 St',
        '82 St-Jackson Hts',
        '85 St-Forest Pkwy',
        '88 St',
        '90 St-Elmhurst Av',
        'Aqueduct Racetrack',
        'Aqueduct-North Conduit Av',
        'Astoria Blvd',
        'Astoria-Ditmars Blvd',
        'Beach 105 St',
        'Beach 25 St',
        'Beach 36 St',
        'Beach 44 St',
        'Beach 60 St',
        'Beach 67 St-Arverne By The Sea',
        'Beach 90 St',
        'Beach 98 St',
        'Briarwood-Van Wyck Blvd',
        'Broad Channel',
        'Broadway',
        'Court Sq',
        'Elmhurst Av',
        'Far Rockaway-Mott Av',
        'Flushing-Main St',
        'Forest Av',
        'Forest Hills-71 Av',
        'Fresh Pond Rd',
        'Grand Av-Newtown',
        'Howard Beach-JFK Airport',
        'Hunters Point Av',
        'Jamaica Center-Parsons-Archer',
        'Jamaica-179 St',
        'Jamaica-Van Wyck',
        'Junction Blvd',
        'Kew Gardens-Union Turnpike',
        'Mets-Willets Point',
        'Middle Village-Metropolitan Av',
        'Northern Blvd',
        'Ozone Park-Lefferts Blvd',
        'Parsons Blvd',
        'Queens Plaza',
        'Queensboro Plaza',
        'Rockaway Blvd',
        'Rockaway Park-Beach 116 St',
        'Seneca Av',
        'Steinway St',
        'Sutphin Blvd',
        'Sutphin Blvd-Archer Av-JFK Airport',
        'Vernon Blvd-Jackson Av',
        'Woodhaven Blvd',
        'Woodhaven Blvd',
        'Woodside-61 St'
    ]
}

